import { mkdir, rm, writeFile, cp } from "node:fs/promises";
import { services } from "../src/data/services.mjs";
import { projects } from "../src/data/projects.mjs";
import { expertise } from "../src/data/expertise.mjs";

const out = new URL("../dist/", import.meta.url);
const suppliedUrl = (process.env.SITE_URL || "").trim();
let siteUrl = "";
if (suppliedUrl) {
  const parsed = new URL(suppliedUrl);
  if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password ||
      parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("SITE_URL must be an HTTP(S) origin, for example https://www.example.com");
  }
  siteUrl = parsed.origin;
}
const routes = [["/", "Home"], ["/about/", "About Us"], ["/services/", "Services"],
  ["/projects/", "Project Experience"], ["/expertise/", "Our Expertise"], ["/contact/", "Contact"]];
const descriptions = {
  "/": "Mining, geotechnical investigation, mine monitoring, mapping and supply support from Geotecnicks Limited, Zambia.",
  "/about/": "Meet Geotecnicks Limited, a Zambian company connecting field observations with practical mining and geotechnical insight.",
  "/services/": "Explore mine monitoring, mapping, photogrammetry, geotechnical services, mining support and general supply.",
  "/projects/": "Explore selected mining and geotechnical project experience from Geotecnicks Limited in Zambia.",
  "/expertise/": "Engineering geology, site investigation, mine monitoring, mapping, photogrammetry and technical interpretation.",
  "/contact/": "Discuss your mining, geotechnical or supply requirement with Geotecnicks Limited by email, telephone or WhatsApp."
};
const esc = value => String(value).replace(/[&<>"]/g, character => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[character]));
const arrow = '<span aria-hidden="true">↗</span>';
const button = (url, text, style = "") => `<a class="button ${style}" href="${esc(url)}">${text}${arrow}</a>`;
const logo = '<img src="/assets/logo.jpg" width="1499" height="414" alt="Geotecnicks Limited" decoding="async">';
const navLink = (url, name, current) => `<a href="${url}"${url === current ? ' aria-current="page"' : ""}>${name}</a>`;
const search = `<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-top"><h2 id="search-title">Find your way.</h2><form method="dialog"><button class="icon-button" aria-label="Close search">×</button></form></div><label for="site-search">Search pages and services</label><input id="site-search" type="search" autocomplete="off" placeholder="Try “mapping” or “projects”"><ul class="search-results">${[...routes.map(([url,name])=>({url,name})),...services.map(s=>({url:`/services/#${s.slug}`,name:s.title}))].map(item=>`<li data-search-item><a href="${item.url}">${esc(item.name)}${arrow}</a></li>`).join("")}</ul><p data-search-empty role="status" hidden>No matching pages or services.</p></dialog>`;
const header = path => `<a class="skip" href="#main">Skip to main content</a><div class="utility"><div class="shell"><span>ZAMBIA <span aria-hidden="true">/</span> MINING &amp; GEOTECHNICAL</span><a href="tel:+260964370473">+260 964 370 473</a></div></div><header class="site-header"><div class="shell nav-wrap"><a class="brand" href="/" aria-label="Geotecnicks Limited home">${logo}</a><div class="nav-controls"><button class="search-toggle icon-button" hidden aria-label="Search website"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><button class="menu" type="button" hidden aria-expanded="false" aria-controls="site-nav"><span class="sr-only">Toggle navigation</span><span aria-hidden="true">Menu <b>☰</b></span></button></div><nav id="site-nav" aria-label="Primary navigation">${routes.map(([url,name])=>navLink(url,name,path)).join("")}</nav></div></header>`;
const footer = `<footer><div class="shell footer-main"><div class="footer-brand">${logo}<p>Upholding sustainable development in mining.</p><p class="footer-note">Practical insight. Grounded in Zambia.</p></div><div><h2>Explore</h2><nav aria-label="Footer navigation">${routes.map(([url,name])=>navLink(url,name)).join("")}</nav></div><div><h2>Start a conversation</h2><a href="mailto:geotecnicks.limited@gmail.com">geotecnicks.limited@gmail.com</a><a href="tel:+260964370473">+260 964 370 473</a><a href="https://wa.me/260964370473">Connect on WhatsApp ↗</a></div></div><div class="shell legal"><span>© <span data-year>2026</span> Geotecnicks Limited</span><span>Mining. Geotechnics. Perspective.</span><a href="#main">Back to top ↑</a></div></footer>`;
const layout = (path, title, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Geotecnicks Limited</title><meta name="description" content="${esc(descriptions[path])}">${siteUrl?`<link rel="canonical" href="${siteUrl}${path}"><meta property="og:url" content="${siteUrl}${path}">`:""}<meta property="og:type" content="website"><meta property="og:site_name" content="Geotecnicks Limited"><meta property="og:title" content="${title} | Geotecnicks Limited"><meta property="og:description" content="${esc(descriptions[path])}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title} | Geotecnicks Limited"><meta name="twitter:description" content="${esc(descriptions[path])}"><meta name="theme-color" content="#132a23"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body>${header(path)}<main id="main" tabindex="-1">${body}</main>${footer}${search}</body></html>`;
const intro = (eyebrow, title, text) => `<section class="page-hero"><div class="shell"><p class="breadcrumb"><a href="/">Home</a> <span aria-hidden="true">/</span> ${eyebrow}</p><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></div><span class="hero-mark" aria-hidden="true">↗</span></section>`;
const sectionHead = (eyebrow, title, link = "") => `<div class="section-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${link}</div>`;
const serviceCards = () => `<div class="service-cards">${services.map((s,i)=>`<article class="service-card"><span class="index">0${i+1} /</span><p class="tagline">${esc(s.tagline)}</p><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><a class="text-link" href="/services/#${s.slug}">Explore service<span class="sr-only">: ${esc(s.title)}</span>${arrow}</a></article>`).join("")}</div>`;
const projectCards = (items=projects) => `<div class="project-grid">${items.map((p,i)=>`<article class="project-card" data-project-card data-category="${p.category.toLowerCase()}"><div class="project-visual visual-${i%4}" aria-hidden="true"><span>GEOTECNICKS / FIELD NOTES</span><b>0${i+1}</b><i></i></div><div class="project-copy"><p class="eyebrow">${esc(p.category)} <span>· ${esc(p.year)}</span></p><h3>${esc(p.title)}</h3><p>${esc(p.scope)}</p><p class="attribution">${esc(p.partner)}</p></div></article>`).join("")}</div>`;
const cta = `<section class="contact-cta"><div class="shell"><div><p class="eyebrow">Your next project</p><h2>Let’s get closer<br>to the ground.</h2></div>${button("/contact/","Discuss your requirement","light")}</div></section>`;
const processSteps = `<ol class="process"><li><span>01</span><h3>Define</h3><p>Understand the question. Agree the scope, methods and outputs.</p></li><li><span>02</span><h3>Observe</h3><p>Gather site information through careful fieldwork and traceable records.</p></li><li><span>03</span><h3>Interpret</h3><p>Connect observations to the geological and operational context.</p></li><li><span>04</span><h3>Communicate</h3><p>Deliver clear findings, with limitations and next steps in view.</p></li></ol>`;
const pages = {
  "/": `<section class="home-hero"><img class="hero-image" src="/assets/mining-landscape.jpg" alt="Illustrative aerial view of terraced mining terrain" width="1659" height="948" fetchpriority="high"><div class="hero-shade"></div><div class="shell hero-content"><p class="eyebrow">Perspective from the ground up</p><h1>Ground insight.<br><em>Stronger</em><br>decisions.</h1><p>Mining and geotechnical expertise.<br>Built around the realities of your site.</p>${button("/services/","Explore our services")}</div><div class="shell hero-bottom"><span>UPHOLDING SUSTAINABLE DEVELOPMENT IN MINING</span><span>AI-generated mining landscape · illustrative</span></div></section><div class="service-strip shell" aria-label="Service shortcuts">${services.map((s,i)=>`<a href="/services/#${s.slug}"><span>0${i+1}</span>${s.slug==="mine-monitoring"?"Monitoring &amp; mapping":s.slug==="geotechnical"?"Geotechnical services":s.slug==="mining"?"Mining support":"General supply"}${arrow}</a>`).join("")}</div><section class="section shell introduction"><div><p class="eyebrow">The Geotecnicks perspective</p><h2>Better understanding.<br>From the ground up.</h2></div><div><p class="lead">Every site has a story. We help you read it.</p><p>Geotecnicks Limited connects field observations, geological knowledge and practical technical support to help clients make informed project decisions in Zambia.</p><a class="text-link" href="/about/">Get to know us ${arrow}</a></div></section><section class="section tint"><div class="shell">${sectionHead("What we do","Focused expertise.<br>Connected thinking.",button("/services/","All services","outline"))}${serviceCards()}</div></section><section class="section shell">${sectionHead("Selected experience","Insight in practice.",button("/projects/","Explore projects","outline"))}${projectCards(projects.slice(0,2))}</section><section class="section dark"><div class="shell">${sectionHead("How we work","A clear path from<br>fieldwork to findings.")}${processSteps}</div></section>${cta}`,
  "/about/": `${intro("About us","Grounded in Zambia.<br>Focused on your site.","Practical technical support, clear communication and a considered approach to every assignment.")}<section class="section shell introduction"><div><p class="eyebrow">Who we are</p><h2>Local context.<br>Technical perspective.</h2></div><div><p class="lead">We help make site information useful.</p><p>Geotecnicks Limited works across mine monitoring, mapping, geotechnical investigation, mining support and general supply. We begin with the question your project needs to answer, then shape the brief around it.</p><p>The company was incorporated in Zambia on 16 July 2014 under registration number 124248. The incorporation date does not imply uninterrupted operations.</p></div></section><section class="about-image"><img src="/assets/mining-landscape.jpg" alt="Illustrative mine benches showing the scale and complexity of ground conditions" width="1659" height="948" loading="lazy"><span>AI-generated mining landscape · illustrative</span></section><section class="section tint"><div class="shell">${sectionHead("Our commitment","Care in the field.<br>Clarity in the findings.")}<div class="values"><article><span class="index">01 /</span><h3>Thoughtful scope</h3><p>Understand the brief, agree responsibilities and choose inputs that fit the assignment.</p></article><article><span class="index">02 /</span><h3>Traceable information</h3><p>Keep observations and records clear enough to follow from fieldwork to interpretation.</p></article><article><span class="index">03 /</span><h3>Useful communication</h3><p>Explain findings, uncertainties and limitations alongside practical next steps.</p></article></div></div></section>${cta}`,
  "/services/": `${intro("Services","Four disciplines.<br>One site perspective.","From monitoring and mapping to ground investigation and supply, our services start with an agreed brief.")}<section class="section shell"><div class="service-jump" aria-label="Jump to a service">${services.map(s=>`<a href="#${s.slug}">${esc(s.tagline)} ↓</a>`).join("")}</div><div class="service-list">${services.map((s,i)=>`<article class="service" id="${s.slug}"><div class="service-title"><p class="eyebrow">0${i+1} / ${esc(s.tagline)}</p><h2>${esc(s.title)}</h2><p class="lead">${esc(s.summary)}</p>${button(`/contact/?service=${s.slug}`,"Discuss this service")}</div><div class="service-content">${s.details.map(([heading,text],j)=>`<details${j===0?" open":""}><summary>${esc(heading)}<span aria-hidden="true">+</span></summary><p>${esc(text)}</p></details>`).join("")}<div class="deliverables"><h3>What we can support</h3><ul>${s.deliverables.map(d=>`<li>${esc(d)}</li>`).join("")}</ul></div></div></article>`).join("")}</div><aside class="notice"><h2>Built around the assignment</h2><p>Scope, equipment availability, methods and specialist support are agreed for each site. Where applicable, methods may refer to ASTM or ISRM guidance and Zambian requirements; this does not imply blanket certification or accreditation.</p></aside></section>${cta}`,
  "/projects/": `${intro("Project experience","Different sites.<br>Practical experience.","A selection of mining and geotechnical assignments where Geotecnicks Limited has provided field or technical support.")}<section class="section shell"><div class="project-toolbar"><div class="filters" role="group" aria-label="Filter projects" hidden><button data-project-filter="all" aria-pressed="true">All projects</button><button data-project-filter="mining" aria-pressed="false">Mining</button><button data-project-filter="geotechnical" aria-pressed="false">Geotechnical</button></div><p data-project-count role="status" aria-live="polite">${projects.length} projects</p></div><h2 class="sr-only">Project list</h2>${projectCards()}<p class="note">Assignment summaries reflect the scope recorded for each project. Discuss relevant experience with us when preparing your brief.</p></section>${cta}`,
  "/expertise/": `${intro("Our expertise","Read the site.<br>Connect the evidence.","Practical disciplines brought together to understand ground conditions and communicate meaningful technical findings.")}<section class="section shell">${sectionHead("Our technical focus","The disciplines behind<br>informed decisions.")}<div class="expertise-grid">${expertise.map((name,i)=>`<article><span class="index">0${i+1} /</span><h3>${esc(name)}</h3><span aria-hidden="true">↗</span></article>`).join("")}</div></section><section class="section dark"><div class="shell">${sectionHead("Our approach","A method that follows<br>the question.")}${processSteps}</div></section>${cta}`,
  "/contact/": `${intro("Contact","Tell us about<br>your next project.","Start with the site, the challenge and the outcome you need. We’ll discuss the right scope together.")}<section class="section shell contact-layout"><div class="contact-details"><p class="eyebrow">Let’s talk</p><h2>Good work starts<br>with a conversation.</h2><address><strong>Geotecnicks Limited</strong><span>Zambia</span><a href="mailto:geotecnicks.limited@gmail.com">geotecnicks.limited@gmail.com ↗</a><a href="tel:+260964370473">+260 964 370 473 ↗</a><a href="https://wa.me/260964370473">Start a WhatsApp conversation ↗</a></address><div class="contact-note"><span class="index">A useful starting point</span><p>Share your project location, the service you have in mind, and any timing or scope requirements.</p></div></div><noscript><p>To make an enquiry, use the email or WhatsApp links above.</p></noscript><form id="enquiry-form" hidden aria-describedby="form-help"><h2>Prepare your enquiry</h2><p id="form-help">This form opens a draft in your email application. You review and send it. No information is sent by this website.</p><div class="form-grid"><label>Full name (required)<input name="name" autocomplete="name" required></label><label>Company or organisation<input name="company" autocomplete="organization"></label><label>Email address (required)<input name="email" type="email" autocomplete="email" required></label><label>Telephone number<input name="telephone" type="tel" autocomplete="tel"></label><label class="wide">Service of interest (required)<select name="service" required><option value="">Choose a service</option>${services.map(s=>`<option value="${s.slug}">${esc(s.title)}</option>`).join("")}</select></label><label class="wide">Project location<input name="location"></label><label class="wide">Enquiry details (required)<textarea name="details" rows="5" required></textarea></label></div><button class="button" type="submit">Continue to email ${arrow}</button><p class="note">If an email application does not open, use <a href="mailto:geotecnicks.limited@gmail.com">direct email</a> or <a href="https://wa.me/260964370473">WhatsApp</a>.</p></form></section>`
};
await rm(out, { recursive:true, force:true });
await mkdir(out, { recursive:true });
await cp(new URL("../src/assets/", import.meta.url), new URL("assets/",out), { recursive:true });
for (const [path,title] of routes) {
  const dir = path === "/" ? out : new URL(`.${path}`,out);
  await mkdir(dir,{recursive:true});
  await writeFile(new URL("index.html",dir),layout(path,title,pages[path]));
}
console.log(`Built ${routes.length} routes in dist${siteUrl ? ` for ${siteUrl}` : " (canonical URLs deferred)"}.`);
