import { mkdir, rm, writeFile, cp } from "node:fs/promises";
import { services } from "../src/data/services.mjs";
import { projects } from "../src/data/projects.mjs";
import { expertise } from "../src/data/expertise.mjs";

const out = new URL("../dist/", import.meta.url);
const siteUrl = (process.env.SITE_URL || "").replace(/\/$/, "");
const routes = [
  ["/", "Home"], ["/about/", "About Us"], ["/services/", "Services"],
  ["/projects/", "Project Experience"], ["/expertise/", "Our Expertise"], ["/contact/", "Contact"]
];
const descriptions = {
  "/": "Geotecnicks Limited provides mining, geotechnical, environmental, construction and general-supply services in Zambia.",
  "/about/": "Learn about Geotecnicks Limited, a Zambian company supporting mining, geotechnical, environmental and construction work.",
  "/services/": "Explore mine monitoring, mapping, photogrammetry, geotechnical, mining, environmental, construction and supply services.",
  "/projects/": "Review documented project experience from Geotecnicks Limited across mining, geotechnical and construction work.",
  "/expertise/": "Explore Geotecnicks Limited discipline areas in site investigation, monitoring, mapping, field services and reporting.",
  "/contact/": "Contact Geotecnicks Limited in Zambia by email, telephone, WhatsApp or a transparent email-based enquiry form."
};

const esc = (s) => String(s).replace(/[&<>\"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const link = (href, label, current) => `<a href="${href}"${current === href ? ' aria-current="page"' : ""}>${label}</a>`;
const header = current => `<a class="skip" href="#main">Skip to main content</a><header class="site-header"><div class="shell nav-wrap"><a class="brand" href="/" aria-label="Geotecnicks Limited home"><span aria-hidden="true">G</span> Geotecnicks Limited</a><button class="menu" type="button" aria-expanded="false" aria-controls="site-nav"><span class="sr-only">Toggle navigation</span><span aria-hidden="true">Menu</span></button><nav id="site-nav" aria-label="Primary navigation">${routes.map(([u,n])=>link(u,n,current)).join("")}</nav></div></header>`;
const footer = `<footer><div class="shell footer-grid"><div><strong>Geotecnicks Limited</strong><p>Grounded insight. Practical delivery.</p><p>Zambia</p></div><nav aria-label="Footer navigation">${routes.map(([u,n])=>link(u,n)).join("")}</nav><div><a href="mailto:geotecnicks.limited@gmail.com">geotecnicks.limited@gmail.com</a><a href="tel:+260964370473">+260 964 370 473</a><a href="https://wa.me/260964370473">WhatsApp</a></div></div><div class="shell legal">© <span data-year>2026</span> Geotecnicks Limited. All rights reserved.</div></footer>`;
const layout = ({path,title,body}) => { const canonical = siteUrl ? `<link rel="canonical" href="${siteUrl}${path}">` : ""; const url = siteUrl ? `${siteUrl}${path}` : path; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Geotecnicks Limited</title><meta name="description" content="${esc(descriptions[path])}">${canonical}<meta property="og:type" content="website"><meta property="og:site_name" content="Geotecnicks Limited"><meta property="og:title" content="${title} | Geotecnicks Limited"><meta property="og:description" content="${esc(descriptions[path])}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title} | Geotecnicks Limited"><meta name="twitter:description" content="${esc(descriptions[path])}"><meta name="theme-color" content="#123c2e"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body>${header(path)}<main id="main">${body}</main>${footer}</body></html>`; };
const intro = (eyebrow,title,text) => `<section class="page-hero"><div class="shell narrow"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></div></section>`;
const cards = (items, limit=items.length) => `<div class="cards">${items.slice(0,limit).map(s=>`<article class="card"><p class="eyebrow">${s.year || "Service"}</p><h3>${s.title}</h3><p>${s.summary || s.scope}</p>${s.partner ? `<p class="attribution">${s.partner}</p>` : `<a class="text-link" href="/services/#${s.slug}">Explore this service <span aria-hidden="true">→</span></a>`}</article>`).join("")}</div>`;

const pages = {
  "/": `${intro("Geotecnicks Limited","Practical ground insight for better project decisions.","Mining, geotechnical, environmental, construction and supply support shaped around the realities of each site.")}<section class="shell actions"><a class="button" href="/contact/">Request a quotation</a><a class="button secondary" href="/services/">Explore services</a></section><section class="section shell split"><div><p class="eyebrow">Grounded insight. Practical delivery.</p><h2>Clear technical support, from fieldwork to reporting</h2></div><p>Geotecnicks Limited works with clients in Zambia to define practical scopes, gather dependable site information and communicate findings clearly. Every engagement begins with the project context and an agreed brief.</p></section><section class="section tint"><div class="shell"><p class="eyebrow">What we do</p><h2>Services for the full project context</h2>${cards(services)} </div></section><section class="section shell feature"><div><p class="eyebrow">Featured service</p><h2>Mine Monitoring, Mapping and Photogrammetry</h2><p>Structured programmes connect site observations with usable records. We distinguish programme design, field monitoring, mapping, interpretation and reporting so responsibilities and outputs remain clear.</p><a class="button" href="/services/#mine-monitoring">View the service</a></div><div class="graphic" role="img" aria-label="Abstract contour lines representing measured ground conditions"><span>Observe</span><span>Map</span><span>Interpret</span></div></section><section class="section shell"><p class="eyebrow">Selected experience</p><h2>Documented projects</h2>${cards(projects,3)}<a class="text-link section-link" href="/projects/">View all project experience →</a></section><section class="section dark"><div class="shell"><p class="eyebrow">Delivery approach</p><h2>Define. Observe. Interpret. Communicate.</h2><ol class="steps"><li><strong>Define</strong><span>Agree the question, scope, method and output.</span></li><li><strong>Observe</strong><span>Capture traceable field information.</span></li><li><strong>Interpret</strong><span>Place findings in their site context.</span></li><li><strong>Communicate</strong><span>Report clearly for practical use.</span></li></ol></div></section><section class="section shell contact-band"><div><p class="eyebrow">Start a conversation</p><h2>Tell us about your site or supply requirement.</h2></div><div><a href="mailto:geotecnicks.limited@gmail.com">Email Geotecnicks Limited</a><a href="tel:+260964370473">Call +260 964 370 473</a><a href="https://wa.me/260964370473">Message on WhatsApp</a></div></section>`,
  "/about/": `${intro("About us","A practical Zambian partner for site-based work.","Geotecnicks Limited was incorporated in Zambia on 16 July 2014 under registration number 124248. This date describes incorporation and does not imply uninterrupted operations.")}<section class="section shell split"><div><p class="eyebrow">Our mission</p><h2>Make site information useful.</h2></div><p>Our mission is to provide clear, practical technical and supply support that helps clients understand site conditions and make informed project decisions.</p></section><section class="section tint"><div class="shell split"><div><p class="eyebrow">Our commitment</p><h2>Thoughtful scope. Careful fieldwork. Clear communication.</h2></div><p>Geotecnicks Limited is committed to understanding each brief, working responsibly within the agreed scope, keeping records traceable and communicating limitations as clearly as findings.</p></div></section><section class="section shell"><p class="eyebrow">Coverage</p><h2>Connected services for real project conditions</h2><p class="measure">Our work spans mining support, geotechnical investigation and interpretation, environmental field services, construction support, and general supply. Services are selected and scoped for the needs of each engagement.</p>${cards(services)}</section>`,
  "/services/": `${intro("Services","Site-focused services, clearly scoped.","Six connected service areas support projects from initial definition and field observations to interpretation, reporting and supply coordination.")}<section class="section shell service-list">${services.map((s,i)=>`<article id="${s.slug}" class="service ${i===0?'featured':''}"><div><p class="eyebrow">${String(i+1).padStart(2,"0")}</p><h2>${s.title}</h2><p>${s.summary}</p></div>${s.details?`<div class="detail-grid">${s.details.map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join("")}</div>`:""}</article>`).join("")}</section><aside class="notice"><div class="shell"><h2>Methods and availability</h2><p>Where relevant, work may refer to applicable ASTM or ISRM methods and Zambian requirements. The method is agreed for the assignment; this wording does not represent blanket certification or regulatory accreditation. Instrument-dependent services depend on site requirements, equipment availability and agreed specialist support.</p></div></aside>`,
  "/projects/": `${intro("Project experience","Selected documented assignments.","A concise record of project contexts in which Geotecnicks Limited has provided field or technical support.")}<section class="section shell"><h2 class="sr-only">Project list</h2>${cards(projects)}<p class="note">Project descriptions are intentionally concise. Additional projects will be published only after their wording is verified from an approved company profile.</p></section>`,
  "/expertise/": `${intro("Our expertise","Disciplines connected by the site context.","Geotecnicks Limited brings together practical disciplines needed to observe ground conditions, structure field information and communicate useful technical findings.")}<section class="section shell"><h2>Discipline areas</h2><div class="expertise-grid">${expertise.map((x,i)=>`<article><span aria-hidden="true">${String(i+1).padStart(2,"0")}</span><h3>${x}</h3></article>`).join("")}</div></section><section class="section tint"><div class="shell split"><h2>Expertise applied to the brief</h2><p>Inputs are selected for the assignment rather than presented as a one-size-fits-all package. Scope, methods, resources, specialist support, deliverables and limitations are agreed for the particular site.</p></div></section>`,
  "/contact/": `${intro("Contact","Let’s discuss the requirement.","Contact Geotecnicks Limited in Zambia. Email and WhatsApp are available directly, or use the form to prepare an email in your own email application.")}<section class="section shell contact-layout"><div class="contact-details"><h2>Company contact</h2><address><strong>Geotecnicks Limited</strong><span>Zambia</span><a href="mailto:geotecnicks.limited@gmail.com">geotecnicks.limited@gmail.com</a><a href="tel:+260964370473">+260 964 370 473</a><a href="https://wa.me/260964370473">WhatsApp: +260 964 370 473</a></address></div><form id="enquiry-form"><h2>Prepare an enquiry email</h2><p id="form-help">Submitting opens your email application. No information is sent by this website.</p><label>Full name <input name="name" autocomplete="name" required></label><label>Company or organisation <input name="company" autocomplete="organization"></label><label>Email address <input name="email" type="email" autocomplete="email" required></label><label>Telephone number <input name="telephone" type="tel" autocomplete="tel"></label><label>Service of interest <select name="service" required><option value="">Choose a service</option>${services.map(s=>`<option>${s.title}</option>`).join("")}</select></label><label>Project location <input name="location"></label><label>Enquiry details <textarea name="details" rows="6" required></textarea></label><button class="button" type="submit">Continue to email</button><p class="note">If your email application does not open, email <a href="mailto:geotecnicks.limited@gmail.com">geotecnicks.limited@gmail.com</a> or use <a href="https://wa.me/260964370473">WhatsApp</a>.</p></form></section>`
};

await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
await cp(new URL("../src/assets/",import.meta.url),new URL("assets/",out),{recursive:true});
for (const [path,title] of routes) { const dir = path === "/" ? out : new URL(`.${path}`,out); await mkdir(dir,{recursive:true}); await writeFile(new URL("index.html",dir),layout({path,title,body:pages[path]})); }
console.log(`Built ${routes.length} routes in dist${siteUrl ? ` for ${siteUrl}` : " (canonical URLs deferred)"}.`);
